ALTER TABLE "domestico" ADD COLUMN IF NOT EXISTS "dom_aluguel" DECIMAL(10, 2) NOT NULL DEFAULT 0;
ALTER TABLE "domestico" ADD COLUMN IF NOT EXISTS "dom_luz" DECIMAL(10, 2) NOT NULL DEFAULT 0;
ALTER TABLE "domestico" ADD COLUMN IF NOT EXISTS "dom_agua" DECIMAL(10, 2) NOT NULL DEFAULT 0;
ALTER TABLE "domestico" ADD COLUMN IF NOT EXISTS "dom_internet" DECIMAL(10, 2) NOT NULL DEFAULT 0;

ALTER TABLE "domestico" DROP CONSTRAINT IF EXISTS "domestico_pkey";
ALTER TABLE "viagem" DROP CONSTRAINT IF EXISTS "viagem_pkey";
